services:
    web:
        image: nginx:alpine
        env_file:
            - ./.env.local
        container_name: '${APP_NAME}-web'
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        env_file:
            - ./.env.local
        container_name: '${APP_NAME}-php'
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/var/www/html

    db_pfwow:
        env_file:
            - ./.env.local
        image: mariadb:10.5.9
        container_name: '${APP_NAME}-db'
        restart: always
        volumes:
            - pfwow_data:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$${MYSQL_ROOT_PASSWORD}
            interval: 5s
            retries: 5

    db_admin:
        env_file:
            - ./.env.local
        image: phpmyadmin/phpmyadmin:5
        container_name: '${APP_NAME}-db-admin'
        ports:
            - '${APP_DB_ADMIN_PORT}:80'
        depends_on:
            db_pfwow:
                condition: service_healthy
        environment:
            - MYSQL_DB_HOST=db_pfwow
            - MYSQL_USER=$${MYSQL_USER}
            - MYSQL_PASSWORD=$${MYSQL_PASSWORD}

    mail:
        image: dockage/mailcatcher:latest
        ports:
            - '${APP_MAIL_PORT}:1025'

volumes:
    pfwow_data:
