services:
    web:
        image: nginx:alpine
        environment:
            - MAILER_DSN=${MAILER_DSN}
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/var/www/html

    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:8.9
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGA_ADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
        depends_on:
            - db

volumes:
    postgres_data:
